
--INSERTION 

BULK INSERT PATIENT FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\PATIENT.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);


BULK INSERT DRUG FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\DRUG.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT DOCTOR FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\DOCTOR.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT SUPPLIER FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\SUPPLIER.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT DRUG_MANUFACTURER FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\DRUG_MANUFACTURER.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT DISTRIBUTOR FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\DISTRIBUTOR.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT DRUG_STORE FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\DRUG_STORE.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT EMPLOYEE FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\EMPLOYEE.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT PRESCRIPTION FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\PRESCRIPTION.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT RECIEPT FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\RECIEPT.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT INVOICE FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\INVOICE.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT PRICE FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\PRICE.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

BULK INSERT STOCK FROM 'C:\Users\DELL\Desktop\SPRING 22\DAMG6210\DMDD project\DATA\STOCK.csv' 
WITH ( 
FIRSTROW = 2,
FIELDTERMINATOR = ',',  
ROWTERMINATOR = '\n',
TABLOCK
);

INSERT INTO PATIENT VALUES ('John', 'Doe', 8572942355, '05/22/1996', 'Male', 'star','ABC1234567', '407 Huntington', 'Boston', 'MA', 02215);
INSERT INTO DOCTOR VALUES ('Tom', 'Doc', 7676656653, 'Cardiology', '319 Huntington', 'Boston', 'MA', 02215);
INSERT INTO PRESCRIPTION VALUES (2, 4, 12, '12/02/2022');
INSERT INTO DRUG VALUES ('Robitussin');
INSERT INTO STOCK VALUES (3, 50, 300, 'X9', 'No');
INSERT INTO PRICE VALUES (20, 25, 10, '05/05/2024', 23, 9);
INSERT INTO DRUG_STORE VALUES (8094820131, '780 Columbus Ave', 'Boston', 'MA', 02215);
INSERT INTO SUPPLIER VALUES ('Emcure Pharma', 6173733490, '41 Summer Street', 'Boston', 'MA', 02118, 'DM');
INSERT INTO RECIEPT VALUES (10, '09/09/2021', 94, 4, 33, 2);
INSERT INTO EMPLOYEE VALUES ('Jack', 'Jill', 7676656653, '123-45-6789','01/02/2002','Salesman', 25,'1029 Boylston', 'Boston', 'MA', 02215, 2);
INSERT INTO INVOICE VALUES (3, 33, 5, 2000, '2021-05-23');
INSERT INTO DRUG_MANUFACTURER VALUES (52,4500000);
INSERT INTO DISTRIBUTOR VALUES (66,'Large');
